[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

# Game:update
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.C.EDITION[2] = 0.7+0.2*(1+math.sin(self.TIMERS.REAL*1.5 + 6))"
position = "after"
payload = '''
for _,v in pairs(SMODS.Gradients) do
   v:update(dt) 
end'''
match_indent = true